apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: demo-flinkdeployment
spec:
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  image: ds01-harbor.venetianqa.local/devops/flink-demo:1.20
  taskManager:
    replicas: 2
    resource:
      cpu: 1
      memory: 4096m
      
