SET 'execution.runtime-mode' = 'streaming';
SET 'table.dynamic-table-options.enabled' = 'true';
SET 'table.exec.sink.upsert-materialize' = 'NONE';

SET 'execution.checkpointing.interval' = '2 min';
SET 'execution.checkpointing.timeout' = '15 min';
SET 'execution.checkpointing.tolerable-failed-checkpoints' = '3';
SET 'execution.checkpointing.min-pause' = '30 s';
SET 'execution.checkpointing.mode' = 'EXACTLY_ONCE';

CREATE CATALOG ${CATALOG} WITH (
  'type' = 'paimon',
  'warehouse' = '${WAREHOUSE}',
  's3.endpoint' = '${S3_ENDPOINT}',
  's3.access-key' = '${S3_ACCESS_KEY}',
  's3.secret-key' = '${S3_SECRET_KEY}',
  's3.path.style.access' = '${S3_PATH_STYLE}'
);

USE CATALOG ${CATALOG};


CREATE DATABASE IF NOT EXISTS ods_ewallet;
USE ods_ewallet;


CREATE DATABASE IF NOT EXISTS dwd;


-- ============================================================
-- Table 1: dwd.ewallet_payments
-- Source: ods_ewallet.Payments
-- Partitioned by: pt_created_date
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_payments (
    id                              BIGINT          COMMENT 'ODS: Id',
    patron_id                       STRING          COMMENT 'ODS: PatronId',
    amount                          DECIMAL(38, 10) COMMENT 'ODS: Amount',
    status                          STRING          COMMENT 'ODS: Status',
    outlet                          STRING          COMMENT 'ODS: Outlet',
    pos_reference                   STRING          COMMENT 'ODS: POSReference',
    remark                          STRING          COMMENT 'ODS: Remark',
    transaction_type                STRING          COMMENT 'ODS: TransactionType',
    device_id                       STRING          COMMENT 'ODS: DeviceId',
    outlet_code                     STRING          COMMENT 'ODS: OutletCode',
    card_tier                       STRING          COMMENT 'ODS: CardTier',
    admin_fee                       DECIMAL(38, 10) COMMENT 'ODS: AdminFee',
    outlet_property                 STRING          COMMENT 'ODS: OutletProperty',
    outlet_shop_no                  STRING          COMMENT 'ODS: OutletShopNo',
    payment_amount                  DECIMAL(38, 10) COMMENT 'ODS: PaymentAmount',
    payment_method                  STRING          COMMENT 'ODS: PaymentMethod',
    remaining_amount                DECIMAL(38, 10) COMMENT 'ODS: RemainingAmount',
    rounding                        DECIMAL(38, 10) COMMENT 'ODS: Rounding',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    modified_time                   TIMESTAMP(3)    COMMENT 'ODS: ModifiedTime',
    modified_by                     STRING          COMMENT 'ODS: ModifiedBy',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    pt_created_date                 INT          COMMENT 'ODS: pt_created_date, partition key by creation date',
    PRIMARY KEY (id, pt_created_date) NOT ENFORCED
) PARTITIONED BY (pt_created_date) WITH (
    'changelog-producer'                    = 'input',
    'merge-engine'                          = 'deduplicate',
    'bucket'                                = '4',
    'snapshot.num-retained.min'              = '5',
    'snapshot.num-retained.max'              = '5000',
    'snapshot.time-retained'                 = '3 d',
    'compaction.async.enabled'               = 'true',
    'num-sorted-run.compaction-trigger'      = '3',
    'num-sorted-run.stop-trigger'            = '9',
    'target-file-size'                       = '128 mb',
    'scan.plan-sort-partition'               = 'true',
    'partition.expiration-time'              = '3650 d',
    'partition.expiration-check-interval'    = '1 d',
    'partition.timestamp-pattern'            = '$$pt_created_date',
    'partition.timestamp-formatter'          = 'yyyyMMdd'
);

INSERT INTO dwd.ewallet_payments
SELECT
    `Id`                            AS id,
    `PatronId`                      AS patron_id,
    `Amount`                        AS amount,
    `Status`                        AS status,
    `Outlet`                        AS outlet,
    `POSReference`                  AS pos_reference,
    `Remark`                        AS remark,
    `TransactionType`               AS transaction_type,
    `DeviceId`                      AS device_id,
    `OutletCode`                    AS outlet_code,
    `CardTier`                      AS card_tier,
    `AdminFee`                      AS admin_fee,
    `OutletProperty`                AS outlet_property,
    `OutletShopNo`                  AS outlet_shop_no,
    `PaymentAmount`                 AS payment_amount,
    `PaymentMethod`                 AS payment_method,
    `RemainingAmount`               AS remaining_amount,
    `Rounding`                      AS rounding,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ModifiedTime`                  AS modified_time,
    `ModifiedBy`                    AS modified_by,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at,
    `pt_created_date`               AS pt_created_date
FROM ods_ewallet.`Payments` /*+ OPTIONS('consumer-id' = 'dwd-ewallet-payments-v1', 'consumer.expiration-time' = '3d') */ WHERE pt_created_date IS NOT NULL;


-- ============================================================
-- Table 2: dwd.ewallet_transaction_details
-- Source: ods_ewallet.TransactionDetails
-- Partitioned by: pt_created_date
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_transaction_details (
    id                              STRING          COMMENT 'ODS: Id',
    balance_detail_id               STRING          COMMENT 'ODS: BalanceDetailId',
    before_detail_balance           DECIMAL(38, 10) COMMENT 'ODS: BeforeDetailBalance',
    amount                          DECIMAL(38, 10) COMMENT 'ODS: Amount',
    expiry_date                     TIMESTAMP(3)    COMMENT 'ODS: ExpiryDate',
    compor_id                       STRING          COMMENT 'ODS: ComporId',
    transaction_type                STRING          COMMENT 'ODS: TransactionType',
    channel                         STRING          COMMENT 'ODS: Channel',
    pos_reference                   STRING          COMMENT 'ODS: POSReference',
    outlet                          STRING          COMMENT 'ODS: Outlet',
    remark                          STRING          COMMENT 'ODS: Remark',
    payment_detail_id               STRING          COMMENT 'ODS: PaymentDetailId',
    payment_id                      BIGINT          COMMENT 'ODS: PaymentId',
    after_detail_balance            DECIMAL(38, 10) COMMENT 'ODS: AfterDetailBalance',
    source_system                   STRING          COMMENT 'ODS: SourceSystem',
    dollar_type_id                  STRING          COMMENT 'ODS: DollarTypeId',
    exception_balance               DECIMAL(38, 10) COMMENT 'ODS: ExceptionBalance',
    patron_id                       STRING          COMMENT 'ODS: PatronId',
    source_key                      STRING          COMMENT 'ODS: SourceKey',
    device_id                       STRING          COMMENT 'ODS: DeviceId',
    after_balance                   DECIMAL(38, 10) COMMENT 'ODS: AfterBalance',
    before_balance                  DECIMAL(38, 10) COMMENT 'ODS: BeforeBalance',
    outlet_code                     STRING          COMMENT 'ODS: OutletCode',
    property                        STRING          COMMENT 'ODS: Property',
    display_source_key              STRING          COMMENT 'ODS: DisplaySourceKey',
    source_system_extra_reference   STRING          COMMENT 'ODS: SourceSystemExtraReference',
    segment_code                    STRING          COMMENT 'ODS: SegmentCode',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    pt_created_date                 INT          COMMENT 'ODS: pt_created_date, partition key by creation date',
    PRIMARY KEY (id, pt_created_date) NOT ENFORCED
) PARTITIONED BY (pt_created_date) WITH (
    'changelog-producer'                    = 'input',
    'merge-engine'                          = 'deduplicate',
    'bucket'                                = '4',
    'snapshot.num-retained.min'              = '5',
    'snapshot.num-retained.max'              = '5000',
    'snapshot.time-retained'                 = '3 d',
    'compaction.async.enabled'               = 'true',
    'num-sorted-run.compaction-trigger'      = '3',
    'num-sorted-run.stop-trigger'            = '9',
    'target-file-size'                       = '128 mb',
    'scan.plan-sort-partition'               = 'true',
    'partition.expiration-time'              = '3650 d',
    'partition.expiration-check-interval'    = '1 d',
    'partition.timestamp-pattern'            = '$$pt_created_date',
    'partition.timestamp-formatter'          = 'yyyyMMdd'
);

INSERT INTO dwd.ewallet_transaction_details
SELECT
    `Id`                            AS id,
    `BalanceDetailId`               AS balance_detail_id,
    `BeforeDetailBalance`           AS before_detail_balance,
    `Amount`                        AS amount,
    `ExpiryDate`                    AS expiry_date,
    `ComporId`                      AS compor_id,
    `TransactionType`               AS transaction_type,
    `Channel`                       AS channel,
    `POSReference`                  AS pos_reference,
    `Outlet`                        AS outlet,
    `Remark`                        AS remark,
    `PaymentDetailId`               AS payment_detail_id,
    `PaymentId`                     AS payment_id,
    `AfterDetailBalance`            AS after_detail_balance,
    `SourceSystem`                  AS source_system,
    `DollarTypeId`                  AS dollar_type_id,
    `ExceptionBalance`              AS exception_balance,
    `PatronId`                      AS patron_id,
    `SourceKey`                     AS source_key,
    `DeviceId`                      AS device_id,
    `AfterBalance`                  AS after_balance,
    `BeforeBalance`                 AS before_balance,
    `OutletCode`                    AS outlet_code,
    `Property`                      AS property,
    `DisplaySourceKey`              AS display_source_key,
    `SourceSystemExtraReference`    AS source_system_extra_reference,
    `SegmentCode`                   AS segment_code,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at,
    `pt_created_date`               AS pt_created_date
FROM ods_ewallet.`TransactionDetails` /*+ OPTIONS('consumer-id' = 'dwd-ewallet-transaction-details-v1', 'consumer.expiration-time' = '3d') */ WHERE pt_created_date IS NOT NULL;
