SET 'execution.runtime-mode' = 'streaming';
SET 'table.dynamic-table-options.enabled' = 'true';
SET 'table.exec.sink.upsert-materialize' = 'NONE';

SET 'execution.checkpointing.interval' = '10s';
SET 'execution.checkpointing.mode' = 'EXACTLY_ONCE';

CREATE CATALOG ${CATALOG} WITH (
  'type' = 'paimon',
  'warehouse' = '${WAREHOUSE}',
  's3.endpoint' = '${S3_ENDPOINT}',
  's3.access-key' = '${S3_ACCESS_KEY}',
  's3.secret-key' = '${S3_SECRET_KEY}',
  's3.path.style.access' = '${S3_PATH_STYLE}'
);

USE CATALOG ${CATALOG};


CREATE DATABASE IF NOT EXISTS ods_ewallet;
USE ods_ewallet;


CREATE DATABASE IF NOT EXISTS dwd;


-- ============================================================
-- Table 1: dwd.ewallet_outlet_types
-- Source: ods_ewallet.OutletTypes
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_outlet_types (
    id                              STRING          COMMENT 'ODS: Id',
    name                            STRING          COMMENT 'ODS: Name',
    is_leased_outlet                BOOLEAN         COMMENT 'ODS: IsLeasedOutlet',
    is_required_enter_payment       BOOLEAN         COMMENT 'ODS: IsRequiredEnterPayment',
    is_required_pos_reference       BOOLEAN         COMMENT 'ODS: IsRequiredPOSReference',
    is_cage                         BOOLEAN         COMMENT 'ODS: IsCage',
    is_display_patron_photo         BOOLEAN         COMMENT 'ODS: IsDisplayPatronPhoto',
    is_e_voucher_redemption         BOOLEAN         COMMENT 'ODS: IsEVoucherRedemption',
    is_payment                      BOOLEAN         COMMENT 'ODS: IsPayment',
    is_print_e_voucher_redemption_slip BOOLEAN      COMMENT 'ODS: IsPrintEVoucherRedemptionSlip',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    modified_time                   TIMESTAMP(3)    COMMENT 'ODS: ModifiedTime',
    modified_by                     STRING          COMMENT 'ODS: ModifiedBy',
    ods_ingested_at                 TIMESTAMP(3)    COMMENT 'ODS: ods_ingested_at',
    ods_updated_at                  TIMESTAMP(3)    COMMENT 'ODS: ods_updated_at',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'changelog-producer' = 'input',
    'merge-engine'       = 'deduplicate',
    'bucket'             = '1'
);

INSERT INTO dwd.ewallet_outlet_types
SELECT
    `Id`                            AS id,
    `Name`                          AS name,
    `IsLeasedOutlet`                AS is_leased_outlet,
    `IsRequiredEnterPayment`        AS is_required_enter_payment,
    `IsRequiredPOSReference`        AS is_required_pos_reference,
    `IsCage`                        AS is_cage,
    `IsDisplayPatronPhoto`          AS is_display_patron_photo,
    `IsEVoucherRedemption`          AS is_e_voucher_redemption,
    `IsPayment`                     AS is_payment,
    `IsPrintEVoucherRedemptionSlip` AS is_print_e_voucher_redemption_slip,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ModifiedTime`                  AS modified_time,
    `ModifiedBy`                    AS modified_by,
    `ods_ingested_at`               AS ods_ingested_at,
    `ods_updated_at`                AS ods_updated_at,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at
FROM ods_ewallet.`OutletTypes`
WHERE `op` IS NULL OR `op` <> 'd';


-- ============================================================
-- Table 2: dwd.ewallet_outlets
-- Source: ods_ewallet.Outlets
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_outlets (
    id                              STRING          COMMENT 'ODS: Id',
    name                            STRING          COMMENT 'ODS: Name',
    is_active                       BOOLEAN         COMMENT 'ODS: IsActive',
    code                            STRING          COMMENT 'ODS: Code',
    outlet_company                  STRING          COMMENT 'ODS: OutletCompany',
    property_id                     STRING          COMMENT 'ODS: PropertyId',
    remarks                         STRING          COMMENT 'ODS: Remarks',
    shop_no                         STRING          COMMENT 'ODS: ShopNo',
    contract                        STRING          COMMENT 'ODS: Contract',
    payment_term                    STRING          COMMENT 'ODS: PaymentTerm',
    segment_id                      STRING          COMMENT 'ODS: SegmentId',
    vendor_code                     STRING          COMMENT 'ODS: VendorCode',
    sys_start_time                  TIMESTAMP(3)    COMMENT 'ODS: SysStartTime',
    sys_end_time                    TIMESTAMP(3)    COMMENT 'ODS: SysEndTime',
    outlet_type_id                  STRING          COMMENT 'ODS: OutletTypeId',
    addresses                       STRING          COMMENT 'ODS: Addresses',
    comp_revenue_code               STRING          COMMENT 'ODS: CompRevenueCode',
    company_name                    STRING          COMMENT 'ODS: CompanyName',
    contact                         STRING          COMMENT 'ODS: Contact',
    contract_effective_date         TIMESTAMP(3)    COMMENT 'ODS: ContractEffectiveDate',
    contract_expiry_date            TIMESTAMP(3)    COMMENT 'ODS: ContractExpiryDate',
    crs_revenue_center_code         STRING          COMMENT 'ODS: CrsRevenueCenterCode',
    emails                          STRING          COMMENT 'ODS: Emails',
    grant_id                        STRING          COMMENT 'ODS: GrantId',
    job_title                       STRING          COMMENT 'ODS: JobTitle',
    payment_method_id               STRING          COMMENT 'ODS: PaymentMethodId',
    phone                           STRING          COMMENT 'ODS: Phone',
    is_support_shiji                BOOLEAN         COMMENT 'ODS: IsSupportShiji',
    shiji_outlet_id                 STRING          COMMENT 'ODS: ShijiOutletId',
    vms_outlet_code                 STRING          COMMENT 'ODS: VMSOutletCode',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    modified_time                   TIMESTAMP(3)    COMMENT 'ODS: ModifiedTime',
    modified_by                     STRING          COMMENT 'ODS: ModifiedBy',
    ods_ingested_at                 TIMESTAMP(3)    COMMENT 'ODS: ods_ingested_at',
    ods_updated_at                  TIMESTAMP(3)    COMMENT 'ODS: ods_updated_at',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'changelog-producer' = 'input',
    'merge-engine'       = 'deduplicate',
    'bucket'             = '1'
);

INSERT INTO dwd.ewallet_outlets
SELECT
    `Id`                            AS id,
    `Name`                          AS name,
    `IsActive`                      AS is_active,
    `Code`                          AS code,
    `OutletCompany`                 AS outlet_company,
    `PropertyId`                    AS property_id,
    `Remarks`                       AS remarks,
    `ShopNo`                        AS shop_no,
    `Contract`                      AS contract,
    `PaymentTerm`                   AS payment_term,
    `SegmentId`                     AS segment_id,
    `VendorCode`                    AS vendor_code,
    `SysStartTime`                  AS sys_start_time,
    `SysEndTime`                    AS sys_end_time,
    `OutletTypeId`                  AS outlet_type_id,
    `Addresses`                     AS addresses,
    `CompRevenueCode`               AS comp_revenue_code,
    `CompanyName`                   AS company_name,
    `Contact`                       AS contact,
    `ContractEffectiveDate`         AS contract_effective_date,
    `ContractExpiryDate`            AS contract_expiry_date,
    `CrsRevenueCenterCode`          AS crs_revenue_center_code,
    `Emails`                        AS emails,
    `GrantId`                       AS grant_id,
    `JobTitle`                      AS job_title,
    `PaymentMethodId`               AS payment_method_id,
    `Phone`                         AS phone,
    `IsSupportShiji`                AS is_support_shiji,
    `ShijiOutletId`                 AS shiji_outlet_id,
    `VMSOutletCode`                 AS vms_outlet_code,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ModifiedTime`                  AS modified_time,
    `ModifiedBy`                    AS modified_by,
    `ods_ingested_at`               AS ods_ingested_at,
    `ods_updated_at`                AS ods_updated_at,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at
FROM ods_ewallet.`Outlets`
WHERE `op` IS NULL OR `op` <> 'd';


-- ============================================================
-- Table 3: dwd.ewallet_payments
-- Source: ods_ewallet.Payments
-- Partitioned by: pt_created_date
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_payments (
    id                              BIGINT          COMMENT 'ODS: Id',
    patron_id                       STRING          COMMENT 'ODS: PatronId',
    amount                          DECIMAL(38, 10) COMMENT 'ODS: Amount',
    status                          STRING          COMMENT 'ODS: Status',
    outlet                          STRING          COMMENT 'ODS: Outlet',
    pos_reference                   STRING          COMMENT 'ODS: POSReference',
    remark                          STRING          COMMENT 'ODS: Remark',
    transaction_type                STRING          COMMENT 'ODS: TransactionType',
    device_id                       STRING          COMMENT 'ODS: DeviceId',
    outlet_code                     STRING          COMMENT 'ODS: OutletCode',
    card_tier                       STRING          COMMENT 'ODS: CardTier',
    admin_fee                       DECIMAL(38, 10) COMMENT 'ODS: AdminFee',
    outlet_property                 STRING          COMMENT 'ODS: OutletProperty',
    outlet_shop_no                  STRING          COMMENT 'ODS: OutletShopNo',
    payment_amount                  DECIMAL(38, 10) COMMENT 'ODS: PaymentAmount',
    payment_method                  STRING          COMMENT 'ODS: PaymentMethod',
    remaining_amount                DECIMAL(38, 10) COMMENT 'ODS: RemainingAmount',
    rounding                        DECIMAL(38, 10) COMMENT 'ODS: Rounding',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    modified_time                   TIMESTAMP(3)    COMMENT 'ODS: ModifiedTime',
    modified_by                     STRING          COMMENT 'ODS: ModifiedBy',
    ods_ingested_at                 TIMESTAMP(3)    COMMENT 'ODS: ods_ingested_at',
    ods_updated_at                  TIMESTAMP(3)    COMMENT 'ODS: ods_updated_at',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    pt_created_date                 STRING          COMMENT 'ODS: pt_created_date, partition key by creation date',
    PRIMARY KEY (id, pt_created_date) NOT ENFORCED
) PARTITIONED BY (pt_created_date) WITH (
    'changelog-producer' = 'input',
    'merge-engine'       = 'deduplicate',
    'bucket'             = '2'
);

INSERT INTO dwd.ewallet_payments
SELECT
    `Id`                            AS id,
    `PatronId`                      AS patron_id,
    `Amount`                        AS amount,
    `Status`                        AS status,
    `Outlet`                        AS outlet,
    `POSReference`                  AS pos_reference,
    `Remark`                        AS remark,
    `TransactionType`               AS transaction_type,
    `DeviceId`                      AS device_id,
    `OutletCode`                    AS outlet_code,
    `CardTier`                      AS card_tier,
    `AdminFee`                      AS admin_fee,
    `OutletProperty`                AS outlet_property,
    `OutletShopNo`                  AS outlet_shop_no,
    `PaymentAmount`                 AS payment_amount,
    `PaymentMethod`                 AS payment_method,
    `RemainingAmount`               AS remaining_amount,
    `Rounding`                      AS rounding,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ModifiedTime`                  AS modified_time,
    `ModifiedBy`                    AS modified_by,
    `ods_ingested_at`               AS ods_ingested_at,
    `ods_updated_at`                AS ods_updated_at,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at,
    `pt_created_date`               AS pt_created_date
FROM ods_ewallet.`Payments`
WHERE `op` IS NULL OR `op` <> 'd';


-- ============================================================
-- Table 4: dwd.ewallet_point_payment_details
-- Source: ods_ewallet.PointPaymentDetails
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_point_payment_details (
    id                              STRING          COMMENT 'ODS: Id',
    patron_id                       STRING          COMMENT 'ODS: PatronId',
    reward_type                     STRING          COMMENT 'ODS: RewardType',
    transaction_type                STRING          COMMENT 'ODS: TransactionType',
    point                           DECIMAL(38, 10) COMMENT 'ODS: Point',
    before_point                    DECIMAL(38, 10) COMMENT 'ODS: BeforePoint',
    after_point                     DECIMAL(38, 10) COMMENT 'ODS: AfterPoint',
    remark                          STRING          COMMENT 'ODS: Remark',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    modified_time                   TIMESTAMP(3)    COMMENT 'ODS: ModifiedTime',
    modified_by                     STRING          COMMENT 'ODS: ModifiedBy',
    ods_ingested_at                 TIMESTAMP(3)    COMMENT 'ODS: ods_ingested_at',
    ods_updated_at                  TIMESTAMP(3)    COMMENT 'ODS: ods_updated_at',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'changelog-producer' = 'input',
    'merge-engine'       = 'deduplicate',
    'bucket'             = '1'
);

INSERT INTO dwd.ewallet_point_payment_details
SELECT
    `Id`                            AS id,
    `PatronId`                      AS patron_id,
    `RewardType`                    AS reward_type,
    `TransactionType`               AS transaction_type,
    `Point`                         AS point,
    `BeforePoint`                   AS before_point,
    `AfterPoint`                    AS after_point,
    `Remark`                        AS remark,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ModifiedTime`                  AS modified_time,
    `ModifiedBy`                    AS modified_by,
    `ods_ingested_at`               AS ods_ingested_at,
    `ods_updated_at`                AS ods_updated_at,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at
FROM ods_ewallet.`PointPaymentDetails`
WHERE `op` IS NULL OR `op` <> 'd';


-- ============================================================
-- Table 5: dwd.ewallet_properties
-- Source: ods_ewallet.Properties
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_properties (
    id                              STRING          COMMENT 'ODS: Id',
    name                            STRING          COMMENT 'ODS: Name',
    is_active                       BOOLEAN         COMMENT 'ODS: IsActive',
    shiji_iptv_interface_code       STRING          COMMENT 'ODS: ShijiIptvInterfaceCode',
    shiji_server_url                STRING          COMMENT 'ODS: ShijiServerUrl',
    rs_property                     STRING          COMMENT 'ODS: RsProperty',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    ods_ingested_at                 TIMESTAMP(3)    COMMENT 'ODS: ods_ingested_at',
    ods_updated_at                  TIMESTAMP(3)    COMMENT 'ODS: ods_updated_at',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'changelog-producer' = 'input',
    'merge-engine'       = 'deduplicate',
    'bucket'             = '1'
);

INSERT INTO dwd.ewallet_properties
SELECT
    `Id`                            AS id,
    `Name`                          AS name,
    `IsActive`                      AS is_active,
    `ShijiIptvInterfaceCode`        AS shiji_iptv_interface_code,
    `ShijiServerUrl`                AS shiji_server_url,
    `RsProperty`                    AS rs_property,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ods_ingested_at`               AS ods_ingested_at,
    `ods_updated_at`                AS ods_updated_at,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at
FROM ods_ewallet.`Properties`
WHERE `op` IS NULL OR `op` <> 'd';


-- ============================================================
-- Table 6: dwd.ewallet_segments
-- Source: ods_ewallet.Segments
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_segments (
    id                              STRING          COMMENT 'ODS: Id',
    code                            STRING          COMMENT 'ODS: Code',
    name                            STRING          COMMENT 'ODS: Name',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    modified_time                   TIMESTAMP(3)    COMMENT 'ODS: ModifiedTime',
    modified_by                     STRING          COMMENT 'ODS: ModifiedBy',
    ods_ingested_at                 TIMESTAMP(3)    COMMENT 'ODS: ods_ingested_at',
    ods_updated_at                  TIMESTAMP(3)    COMMENT 'ODS: ods_updated_at',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'changelog-producer' = 'input',
    'merge-engine'       = 'deduplicate',
    'bucket'             = '1'
);

INSERT INTO dwd.ewallet_segments
SELECT
    `Id`                            AS id,
    `Code`                          AS code,
    `Name`                          AS name,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ModifiedTime`                  AS modified_time,
    `ModifiedBy`                    AS modified_by,
    `ods_ingested_at`               AS ods_ingested_at,
    `ods_updated_at`                AS ods_updated_at,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at
FROM ods_ewallet.`Segments`
WHERE `op` IS NULL OR `op` <> 'd';


-- ============================================================
-- Table 7: dwd.ewallet_transaction_details
-- Source: ods_ewallet.TransactionDetails
-- Partitioned by: pt_created_date
-- ============================================================
CREATE TABLE IF NOT EXISTS dwd.ewallet_transaction_details (
    id                              STRING          COMMENT 'ODS: Id',
    balance_detail_id               STRING          COMMENT 'ODS: BalanceDetailId',
    before_detail_balance           DECIMAL(38, 10) COMMENT 'ODS: BeforeDetailBalance',
    amount                          DECIMAL(38, 10) COMMENT 'ODS: Amount',
    expiry_date                     TIMESTAMP(3)    COMMENT 'ODS: ExpiryDate',
    compor_id                       STRING          COMMENT 'ODS: ComporId',
    transaction_type                STRING          COMMENT 'ODS: TransactionType',
    channel                         STRING          COMMENT 'ODS: Channel',
    pos_reference                   STRING          COMMENT 'ODS: POSReference',
    outlet                          STRING          COMMENT 'ODS: Outlet',
    remark                          STRING          COMMENT 'ODS: Remark',
    payment_detail_id               STRING          COMMENT 'ODS: PaymentDetailId',
    payment_id                      BIGINT          COMMENT 'ODS: PaymentId',
    after_detail_balance            DECIMAL(38, 10) COMMENT 'ODS: AfterDetailBalance',
    source_system                   STRING          COMMENT 'ODS: SourceSystem',
    dollar_type_id                  STRING          COMMENT 'ODS: DollarTypeId',
    exception_balance               DECIMAL(38, 10) COMMENT 'ODS: ExceptionBalance',
    patron_id                       STRING          COMMENT 'ODS: PatronId',
    source_key                      STRING          COMMENT 'ODS: SourceKey',
    device_id                       STRING          COMMENT 'ODS: DeviceId',
    after_balance                   DECIMAL(38, 10) COMMENT 'ODS: AfterBalance',
    before_balance                  DECIMAL(38, 10) COMMENT 'ODS: BeforeBalance',
    outlet_code                     STRING          COMMENT 'ODS: OutletCode',
    property                        STRING          COMMENT 'ODS: Property',
    display_source_key              STRING          COMMENT 'ODS: DisplaySourceKey',
    source_system_extra_reference   STRING          COMMENT 'ODS: SourceSystemExtraReference',
    segment_code                    STRING          COMMENT 'ODS: SegmentCode',
    created_time                    TIMESTAMP(3)    COMMENT 'ODS: CreatedTime',
    created_by                      STRING          COMMENT 'ODS: CreatedBy',
    ods_ingested_at                 TIMESTAMP(3)    COMMENT 'ODS: ods_ingested_at',
    ods_updated_at                  TIMESTAMP(3)    COMMENT 'ODS: ods_updated_at',
    dwd_create_at                   TIMESTAMP(3)    COMMENT 'DWD record creation timestamp, generated by CURRENT_TIMESTAMP',
    dwd_update_at                   TIMESTAMP(3)    COMMENT 'DWD record update timestamp, generated by CURRENT_TIMESTAMP',
    pt_created_date                 STRING          COMMENT 'ODS: pt_created_date, partition key by creation date',
    PRIMARY KEY (id, pt_created_date) NOT ENFORCED
) PARTITIONED BY (pt_created_date) WITH (
    'changelog-producer' = 'input',
    'merge-engine'       = 'deduplicate',
    'bucket'             = '2'
);

INSERT INTO dwd.ewallet_transaction_details
SELECT
    `Id`                            AS id,
    `BalanceDetailId`               AS balance_detail_id,
    `BeforeDetailBalance`           AS before_detail_balance,
    `Amount`                        AS amount,
    `ExpiryDate`                    AS expiry_date,
    `ComporId`                      AS compor_id,
    `TransactionType`               AS transaction_type,
    `Channel`                       AS channel,
    `POSReference`                  AS pos_reference,
    `Outlet`                        AS outlet,
    `Remark`                        AS remark,
    `PaymentDetailId`               AS payment_detail_id,
    `PaymentId`                     AS payment_id,
    `AfterDetailBalance`            AS after_detail_balance,
    `SourceSystem`                  AS source_system,
    `DollarTypeId`                  AS dollar_type_id,
    `ExceptionBalance`              AS exception_balance,
    `PatronId`                      AS patron_id,
    `SourceKey`                     AS source_key,
    `DeviceId`                      AS device_id,
    `AfterBalance`                  AS after_balance,
    `BeforeBalance`                 AS before_balance,
    `OutletCode`                    AS outlet_code,
    `Property`                      AS property,
    `DisplaySourceKey`              AS display_source_key,
    `SourceSystemExtraReference`    AS source_system_extra_reference,
    `SegmentCode`                   AS segment_code,
    `CreatedTime`                   AS created_time,
    `CreatedBy`                     AS created_by,
    `ods_ingested_at`               AS ods_ingested_at,
    `ods_updated_at`                AS ods_updated_at,
    CURRENT_TIMESTAMP               AS dwd_create_at,
    CURRENT_TIMESTAMP               AS dwd_update_at,
    `pt_created_date`               AS pt_created_date
FROM ods_ewallet.`TransactionDetails`
WHERE `op` IS NULL OR `op` <> 'd';
